project_id = "eaadywgpoyckqqpiawvu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-claim]
verify_jwt = false

[functions.analyze-claims]
verify_jwt = false
